<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Monthly Low Stock Report - {{ $month->format('F Y') }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 20px;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }

        .header h1 {
            margin: 0;
            font-size: 20px;
        }

        .header p {
            margin: 5px 0;
            color: #666;
        }

        .info-section {
            margin-bottom: 20px;
        }

        .info-section table {
            width: 100%;
        }

        .info-section td {
            padding: 3px 0;
        }

        .info-section td:first-child {
            width: 150px;
            font-weight: bold;
        }

        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        table.data-table th {
            background-color: #f0f0f0;
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
            font-weight: bold;
        }

        table.data-table td {
            border: 1px solid #ddd;
            padding: 6px;
        }

        table.data-table tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        .warning {
            background-color: #fff3cd !important;
        }

        .critical {
            background-color: #f8d7da !important;
        }

        .footer {
            margin-top: 30px;
            padding-top: 10px;
            border-top: 1px solid #ddd;
            font-size: 10px;
            color: #666;
            text-align: center;
        }

        .text-right {
            text-align: right;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>MONTHLY LOW STOCK REPORT</h1>
        <p>{{ $month->format('F Y') }}</p>
        <p>As of {{ $generatedAt->format('d M Y') }}</p>
    </div>

    <div class="info-section">
        <table>
            <tr>
                <td>Generated At:</td>
                <td>{{ $generatedAt->format('d F Y H:i:s') }}</td>
            </tr>
            <tr>
                <td>Generated By:</td>
                <td>{{ $generatedBy }}</td>
            </tr>
            <tr>
                <td>Products Below Minimum:</td>
                <td>{{ count($reportData['items']) }}</td>
            </tr>
        </table>
    </div>

    <table class="data-table">
        <thead>
            <tr>
                <th>SKU</th>
                <th>Product Name</th>
                <th>Category</th>
                <th class="text-right">Current Stock</th>
                <th class="text-right">Minimum Stock</th>
                <th class="text-right">Shortage</th>
            </tr>
        </thead>
        <tbody>
            @forelse($reportData['items'] as $item)
                <tr class="{{ $item['current_stock'] == 0 ? 'critical' : 'warning' }}">
                    <td>{{ $item['sku'] }}</td>
                    <td>{{ $item['name'] }}</td>
                    <td>{{ $item['category'] ?? '-' }}</td>
                    <td class="text-right">{{ number_format($item['current_stock']) }}</td>
                    <td class="text-right">{{ number_format($item['minimum_stock']) }}</td>
                    <td class="text-right">{{ number_format($item['shortage']) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" style="text-align: center; padding: 20px;">
                        All products are above minimum stock levels
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>This is a computer-generated report. Generated on {{ $generatedAt->format('d F Y H:i:s') }}</p>
        <p>Note: Red rows indicate out of stock items, yellow rows indicate low stock items</p>
    </div>
</body>

</html>
